# Generated by Django 5.1.7 on 2025-03-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_song_artist_alter_song_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='spotify_preview_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(max_length=500),
        ),
    ]
