# Generated by Django 5.1.7 on 2025-03-15 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_spotify_preview_url_alter_song_tags'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('play', 'Played song'), ('like', 'Liked song'), ('unlike', 'Unliked song'), ('skip', 'Skipped song'), ('addPlaylist', 'Added to playlist'), ('removePlaylist', 'Removed from playlist'), ('replay', 'Replayed song'), ('search', 'Searched song')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
