### Register a new user
POST http://localhost:8000/api/users/register/
Content-Type: application/json

{
  "username": "testuser",
  "password": "Test1234"
}

### Login user
POST http://localhost:8000/api/users/login/
Content-Type: application/json

{
  "username": "testuser",
  "password": "Test1234"
}

### See user information
GET http://localhost:8000/api/users/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDE2NTY2LCJpYXQiOjE3NDEwMTYyNjYsImp0aSI6IjdiMDI2NmQ4NThjZTQ1N2U5MjQ3NjNiMWZmYjIyMjQ2IiwidXNlcl9pZCI6MX0.g1aZcTZ-vreFe_7KNMsz_JkquTqA1BWX7RE9TKQl37A

### See songs
GET http://localhost:8000/api/songs

### Search songs
GET http://localhost:8000/api/songs/search/?q=nirvana

### Recommend songs
GET http://localhost:8000/api/recommender/recommend/

