# Generated by Django 5.1.7 on 2025-03-16 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_type', models.CharField(choices=[('play', 'Played song'), ('like', 'Liked song'), ('unlike', 'Unliked song'), ('skip', 'Skipped song'), ('addPlaylist', 'Added to playlist'), ('removePlaylist', 'Removed from playlist'), ('replay', 'Replayed song'), ('search', 'Searched song')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
