# Generated by Django 5.1.7 on 2025-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='trained_on',
            field=models.BooleanField(default=False),
        ),
    ]
