# Generated by Django 5.1.7 on 2025-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_useractivity_trained_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('play', 'Played song'), ('like', 'Liked song'), ('unlike', 'Unliked song'), ('skip', 'Skipped song'), ('addPlaylist', 'Added to playlist'), ('removePlaylist', 'Removed from playlist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
